"""Add password field in user table

Revision ID: 834e15eac3b2
Revises: 6e1ec541af29
Create Date: 2024-07-13 22:30:48.709728

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '834e15eac3b2'
down_revision: Union[str, None] = '6e1ec541af29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'password', sa.String(), nullable=False))
    op.alter_column('users', 'token',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
