services:
  db:
    container_name: account_manager_db
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - piggy_bank_network
    restart: unless-stopped
  app:
    container_name: piggy_bank_app
    image: piggy_bank:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - piggy_bank_network
    depends_on:
      - db
    restart: on-failure
    volumes:
      - .:/app
    entrypoint: ["uvicorn", "account_managment.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
networks:
  piggy_bank_network:
    driver: bridge