services:
  db:
    container_name: account_manager_db_prod
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - piggy_bank_network
    restart: unless-stopped
  app:
    container_name: piggy_bank_app_prod
    image: flaviodev99/piggy_bank_server:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    networks:
      - piggy_bank_network
    depends_on:
      - db
    restart: on-failure
networks:
  piggy_bank_network:
    driver: bridge
