name: Deploy to Render

on:
  push:
    branches:
      - develop

jobs:
  deploy_render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    permissions:
      actions: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          github-token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{github.repository}}
          run-id: ${{github.run_id}}

      - name: show files
        run: ls -la

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"

      - name: Install dependencies
        run: python -m pip install ./dist/*.whl

      - name: Show environment
        run: |
          echo "RENDER_API_KEY: $RENDER_API_KEY"
          echo "DOCKER_IMAGE_PATH: $DOCKER_IMAGE_PATH"

      - name: Deploy to Render
        run: |
          python deploy_render.py
