name: Pipeline

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ feature/* ]

jobs:
  install_project:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: login docker
        if: github.event_name == 'push' && github.branch == 'develop'
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6.7.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/piggy_bank_server:latest